In [1]:
import cv2 as cv
import numpy as np

### 공통 parameter

- img : 도형을 그릴 이미지
- color : BGR 색상 정보. 튜플로 입력한다. 예를 들어 (255, 0, 0)은 파란색이다. 흑백을 만들려면 1차원을 입력하면 된다.
- thickness : 선, 원 등의 두께를 정한다. 원 따위의 도형에 -1을 입력하면 칠도형이 된다. 기본값은 1이다.
- lineType : Type of line, whether 8-connected, anti-aliased line etc. By default, it is 8-connected. cv.LINE_AA gives anti-aliased line which looks great for curves.

In [141]:
# 검은 이미지 만들기

img = np.zeros((512,512,3), np.uint8)

In [142]:
# 두꼐가 픽셀인 대각선 그리기

cv.line(img, (0,512), (512,0), (255,0,0), 5)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       ...,

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [143]:
# 응용

img = np.zeros((512,512,3), np.uint8)
cv.imshow("img", img)
while True:
    if cv.waitKey(0) == ord('l'):
        cv.line(img, (0,512), (512,0), (255,0,0), 5)
        cv.imshow("img2", img)
    elif cv.waitKey(0) == ord('q'):
        cv.destroyAllWindows()
        break

In [144]:
# 직사각형 그리기

cv.rectangle(img, (384,0), (510,128), (0,255,0), 5)
cv.imshow("rectangle", img)
cv.waitKey(0)

113

In [145]:
cv.destroyAllWindows()

In [146]:
# 원 그리기

cv.circle(img, (447,63), 63, (0,0,255), -1)
cv.imshow("circle", img)
cv.waitKey()

113

In [147]:
cv.destroyAllWindows()

In [148]:
# 타원 그리기
# 이미지, 원 중심, (가장 긴 반지름, 가장 짧은 반지름), 회전각도, 시작각도, 끝각도, 색상, 두께

cv.ellipse(img, (256, 256), (100,50), 0, 0, 180, 255, -1)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       ...,

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [149]:
cv.imshow("ellips", img)
if cv.waitKey(0) == ord('q'):
    cv.destroyAllWindows()

In [150]:
# 다각형 그리기

pts = np.array([[10,5],[20,30],[70,20],[50,10]], np.int32)
pts

array([[10,  5],
       [20, 30],
       [70, 20],
       [50, 10]])

In [151]:
# 모양을 만들어준다.

pts.reshape((-1, 1, 2))

array([[[10,  5]],

       [[20, 30]],

       [[70, 20]],

       [[50, 10]]])

In [152]:
# 요렇게도 할 수 있겠군

pts = np.expand_dims(pts, 1)

In [153]:
pts

array([[[10,  5]],

       [[20, 30]],

       [[70, 20]],

       [[50, 10]]])

In [154]:
cv.polylines(img, [pts], True, (0,255,255))

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       ...,

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [155]:
cv.imshow("poly", img)

while 1:
    if cv.waitKey(0) == ord("q"):
        cv.destroyAllWindows()
        break

In [156]:
font = cv.FONT_HERSHEY_SIMPLEX
cv.putText(img, "OpenCV", (10,500), font, 4, (255,255,255), 2, cv.LINE_AA)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       ...,

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [157]:
cv.imshow("text", img)

while 1:
    if cv.waitKey(0) == ord("q"):
        cv.destroyAllWindows()
        break

## Exercise
OpenCV의 로고를 그려보시오.

In [48]:
logo = np.zeros((512,512,3), dtype=np.uint8)

In [3]:
512/4

128.0

In [5]:
red = (0,0,255)
blue = (255,0,0)
green = (0,255,0)

In [5]:
270+45

315

In [49]:
logo_raw = logo.copy()

In [50]:
logo = logo_raw.copy()
cv.ellipse(logo, (128, 384), (80,80), 0, 0, 270, green, 40)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [39]:
cv.imshow("logo", logo)
while 1:
    if cv.waitKey(0)  == ord('q'):
        cv.destroyAllWindows()
        break

In [51]:
logo_green = logo.copy()

In [52]:
cv.ellipse(logo,(384,384), (80,80), 315, 0, 270, blue, 40)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [53]:
cv.imshow("logo", logo)
while 1:
    if cv.waitKey(0)  == ord('q'):
        cv.destroyAllWindows()
        break

In [54]:
logo_green_blue = logo.copy()

In [58]:
logo = logo_green_blue.copy()

In [59]:
cv.ellipse(logo, (256, 128), (80,80), 135, 0, 270, red, 40)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [60]:
cv.imshow("logo", logo)
while 1:
    if cv.waitKey(0)  == ord('q'):
        cv.destroyAllWindows()
        break

In [62]:
logo_green_blue_red = logo.copy()

In [81]:
logo = logo_green_blue_red.copy()

In [82]:
cv.putText(logo, "OpenCV", (20,256), cv.FONT_HERSHEY_SIMPLEX, 4, (255, 255, 255), 10, cv.LINE_AA)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [84]:
cv.imshow("logo", logo)
while 1:
    if cv.waitKey(0)  == ord('q'):
        cv.destroyAllWindows()
        break